# Generated by Django 5.0.3 on 2024-04-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='condition',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='character',
            name='accessories',
            field=models.ManyToManyField(to='main_app.accessory'),
        ),
    ]
